### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Factral** [cognophile/Deskcal#7]
Sadge 

![image](https://user-images.githubusercontent.com/74687828/104815786-b2de3880-57e4-11eb-8c4b-bf2af5573c42.png)

**Comment by PlaidRadish** [comment]
I have the same issue on Catalina...

Is there no way to authorize?

> ![image](https://user-images.githubusercontent.com/74687828/104815786-b2de3880-57e4-11eb-8c4b-bf2af5573c42.png)

**Comment by cognophile** [comment]
Thanks for reporting the issue. Looks like it's due to some (sensible) security changes Google implemented to further protect against MITM attacks ([blog post](https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html)) from non-standard browsers. 

I'll look into it further and make some changes when I can find the time.

**Comment by PlaidRadish** [comment]
Awesome! Also, I don't have this problem on my GSuite account at my workplace. It only seems to be happening on my public/free gmail.com account. 

FYI: I temporarily turned off the heightened security for that account to see if that resolved anything, but the same error pops up.

thanks!
